examples/org-level-single-region/README.md
examples/project-level-multi-region/README.md
examples/project-level-multi-region/main.tf
examples/project-level-multi-region/versions.tf
examples/project-level-single-region/README.md
scripts/ci_tests.sh

This PR cleans up the formatting for the examples and adds an example for project-level multi-region integration.
Used `make ci` to validate the changes.
N/A

docs: updated examples and added project-level multi-region

---

main.tf

This PR makes creation of the Snapshot Creation role conditional upon the module being run with `global = True` 
Used `make ci` and @ammarekbote is testing in his lab as well.
N/A

fix: conditionally create the role for project-level snapshot creation

---

main.tf

Simplifying the `GCP_ORG_ID` value to eliminate the prefix.  The value will be and empty string if the scanning project is not in an organization.
Tested in an project-level multi-region deployment which is not in an org.
N/A

fix: removed prefix from `GCP_ORG_ID` env var

---

examples/project-level-multi-region/main.tf
main.tf

Bucket missing for multi region deployment
Deployed the jobs with new changes and verified bucket is populated for all region jobs.
Bucket is not populated for cloud run jobs in multi region deployment

fix: derive bucket name for regional deployments

---

custom_roles.tf
main.tf
output.tf
variables.tf

This PR refactors the custom role creation declarations to a new file and adds more comments. 
Also the 3 service accounts are tagged as following and mentioned in comments wherever they are used
-  Lacework Integration Service Account
-  Orchestrate Service Account
-  Scan Service Account
Deployed a single region and multi region configuration and verified that scan results are generated.

Move custom role creation to a new file

---

custom_roles.tf

The roles created in monitored project do not need to create snapshot in them.
Removing the excess permissions.
Deployed scanner with the changes and there were no regressions.

chore: remove unnecessary permissions

---

examples/org-level-single-region/main.tf
examples/project-level-single-region/main.tf
main.tf
variables.tf

This is part of the work of multi-volume (secondary volume) and stopped instances scanning features for agentless workload scanning. We are finishing up the feature by adding a toggle / boolean for integrations to indicate if they want to turn on Multi-Volume scanning and/or Stopped Instances scanning. This is handled on the backend (in sidekick) to "turn on" the feature if the boolean is set to true.
Last part of: https://github.com/lacework/go-sdk/pull/1275, https://github.com/lacework/terraform-provider-lacework/pull/484
Tested by running terraform locally to confirm the variables came through properly:
https://lacework.atlassian.net/browse/RAIN-54831

Add multi volume variable

---

main.tf
variables.tf

Summary
This is part of the work of multi-volume (secondary volume) and stopped instances scanning features for agentless workload scanning. We are finishing up the feature by adding a toggle / boolean for integrations to indicate if they want to turn on Multi-Volume scanning and/or Stopped Instances scanning. This is handled on the backend (in sidekick) to "turn on" the feature if the boolean is set to true.
Last part of: https://github.com/lacework/go-sdk/pull/1275, https://github.com/lacework/terraform-provider-lacework/pull/484
How did you test this change?
Tested by running terraform locally to confirm the variables came through properly:
Issue
https://lacework.atlassian.net/browse/RAIN-54831

feat(RAIN-54831): Add multi volume & scan stopped instances variables

---

custom_roles.tf

Add permissions to scanner role associated with service account used to launch compute instances.
This allows the scanner container to issue (self) deletion request once the scanning is done and reduce the cleanup time.
Verified no error messages seen while (self) deleting the compute instance

Allow scanner to terminate host compute instance

---

main.tf

Currently, the cloud scheduler trigger is associated with default compute service account.
In certain deployments, the default service account is disabled by default.
As scanner deploys custom service accounts, these accounts can instead be used for the trigger.
Deploy scanner with changes and verify that the trigger works.
https://lacework.atlassian.net/browse/LINK-1917

update cloud schedule trigger to be run by orchestrate email

---

custom_roles.tf

`compute.machineTypes.get` is needed to fetch metadata for compute instances
Deployed with the the new changes to verify there are no regressions.
https://lacework.atlassian.net/browse/LINK-1916

add permision to derive machine info from monitored projects

---

main.tf

Secret creation and service account creation can occur in parallel. Both refer to the email address derived as local variable and there is no implicit dependency between the two resources.
This leaves a possibility that when iam policy for secret is added, the service account is not yet created.
For a Gcp integration, I observed that the secret could not be accessed by the orchestrate account. Adding the dependency indicated that terraform would create this again and also the secret could be accessed later after the rerun.

fix: add dependency for secret iam on orchestrate account creation

---

README.md
main.tf

Scanner compute instances are launched with scan service account.
Recent changes on the scanner are sending an api request to lacework platform as part of first run. 
To make the api request, the scanner service account needs to access the secret value. 
This PR adds `agentless_scan_service_account_email` as one of the service principals that accesses the secret value.
Ran the terraform and verified the scanner service account has the permissions to access the secret value now. 
https://lacework.atlassian.net/browse/AWLS-121

allow scanner compute instance to access secret value

---

README.md
examples/custom-vpc-network/main.tf
main.tf
variables.tf

Add a feature supported in the agentless-aws terraform provider but not GCP: ability to pass environment variables to the cloud run task.
N/A, reported internally.

feat: pass environment variables to cloud run task from terraform

---

main.tf
output.tf
variables.tf

It came to my attention that a customer had `organization/<id>` as the `organization_id` in their main.tf and later on had trouble changing it. This PR adds a quick validator to prevent future cases like this.
modify org level multi region example main.tf and run `terraform plan`. observe that invalid organization id was caught.

misc: add validator for organization id

---

.github/workflows/nightly.yml
.github/workflows/test-compat-pr-comment.yml
.github/workflows/test-compatibility.yml

This modules requires Terraform 1.4 and higher. Setting test workflow parameters to ensure that tests don't fail due to a lower version being tested. 
https://lacework.atlassian.net/browse/GROW-2760

ci: set minimum TF version for test workflows

---

.github/workflows/nightly.yml

There was a missing character in the input field name. 
https://lacework.atlassian.net/browse/GROW-2874

ci: fix typo in nightly workflow

---

README.md
custom_roles.tf
main.tf

To support RG v2, we'll need to query for folder and organization information. That entails the following perms:
* resourcemanager.folders.get
* resourcemanager.organizations.get
This PR adds those two perms. For org-level integration this is trivial, because I can just add those two permissions to the existing perm list. For project-level integration I need to create a separate org-level custom role, because those two permissions only exist at org-level and GCP wouldn't allow you to add those perms to a project-level role.
Happy to hear suggestions on better implementations.
Related PR: https://github.com/lacework-dev/sidekick/pull/1094 
deployed with both `org-level-multi-region` and `project-level-multi-region` examples and inspect analyze.ndjson files to verify that tags are generated …

misc: add more permissions that are needed for resource group v2

---

README.md
checks.tf
custom_roles.tf
main.tf
versions.tf

While working on #74 I noticed that `organization_id` isn't consistently set, so I went through all the example files and ensured it's used in a consistent way. In details:
1. if `organization_id` is not provided, we try to derive it w/ the provider `project_id`
2. we fail to do that, we warn users 
3. in places where `organization_id` is used, we consistently use the derived `local.organization_id` instead of user-provided `var.organization_id`. 
I also updated the min version requirements because minimum TF 1.5 is needed to support `checks` block. This makes it consistent w/ the Azure TF repo. 
1. Go through all example main.tf, add a valid provider project_id, and observe `terraform apply` goes through.
2. Remove project_id and observe `checks` kick in …

misc: use organization_id smarter

---

main.tf

Upon manual inspection, I noticed this condition wasn't quite right given #75. The side-effect of #75 is that we'd expect even project-level integration to have an organization id. However, this would break the assumption in this condition.
This PR corrected the condition (and also made the intention explicit). 
Deploy onto two examples:
`project-level-multi-region`, and `org-level-multi-region`. Observe the resource_id gets corrected in the former, whereas not changes in the latter.

fix: use right resource id in project-level intg

---

README.md
output.tf

Add an output to capture Lacework integration GUID

feat(GROW-2928): Add an output to capture Lacework integration GUID

---

README.md
examples/custom-vpc-network/main.tf
examples/custom-vpc-network/versions.tf
examples/org-level-multi-region/versions.tf
examples/org-level-single-region/versions.tf
examples/project-level-multi-region/main.tf
examples/project-level-multi-region/versions.tf
examples/project-level-single-region/main.tf
examples/project-level-single-region/versions.tf
versions.tf

Per discussion on Slack, we need this version updated and also include `organization_id` for project-level integration because we need to support the creation of an additional role (#74 ). Sometimes the `organization_id` can't be inferred, so in our example we explicitly include it.
deploy example tf files and observe it works.

chore: update version and add org_id in examples

---

custom_roles.tf

**Add permission required by org-level agentless scanning integration to call the GCP Get Project API.**
https://github.com/lacework/terraform-gcp-agentless-scanning/pull/52 modified the _Lacework Agentless Workload Scanning Role for monitored project (Create Snapshots)_, adding a required permission used to call Get Project GCP API. This resolved an issue in the case of project-level agentless scanning integrations, but the issue is still present in the case of org-level agentless scanning integrations. 
The same permission should've also been added to the role used by org-level integrations in that PR, but it wasn't — this PR adds the required permission in that role to resolve the issue in the case of org-level integrations as well.
Prior to this change, we were seeing the get project …

fix(AWLS2-398): Add get project permission to org snapshot role

---

examples/custom-vpc-network/README.md
examples/org-level-multi-region/README.md
examples/org-level-single-region/README.md
examples/project-level-multi-region/README.md
examples/project-level-single-region/README.md

The examples in this repo were a bit out of date, and they no longer match the examples given in the Fortinet documentation. This PR cleans things up. In particular, this changeset:
1. Updates the README examples to contain an up-to-date `versions.tf`
2. Updates the google TF provider to contain a `project` field, since this is now required
3. Adds annotations to explain certain variables and options, where appropriate.
4. Adds the "organization ID" to project level example READMEs, since this is now a required field for project level integrations. The examples themselves already contained these fields.
Special focus was given to getting the README files up-to-date since in the near future, the Fortinet documentation won't contain Terraform examples at all; the docs will simply point to …

fix: update Terraform examples

---

scripts/release_helpers.sh

We hit this CI error while attempting a release: https://github.com/lacework/terraform-gcp-agentless-scanning/actions/runs/17411138516/job/49428594242
The important part reads: 
```
'git whatchanged' is nominated for removal.
If you still use this command, please add an extra
option, '--i-still-use-this', on the command line
```
.... I am adding this option so the verification doesn't fail and we can proceed with our release.
Proof is in the pudding. A green "verify release" CI run means the change worked.
N/A

fix: add option for git whatchanged

---

checks.tf

The last changeset removed the requirement for specifying an `organization_id` in `PROJECT` level integrations.
Unfortunately, my changes to the Terraform check for this variable had an error. As a result we are firing the "you must include an org ID" for all integrations still.
This PR rectifies that problem.
I created a local terraform integration with this change. I verified that:
1. When integration type is `PROJECT` and no organization id is specified, we do not get the warning.
2. When integration type is `ORGANIZATION` and no organization id is specified, we do get the warning.
3. 2. When integration type is `ORGANIZATION` and an organization id is specified, we do not get the warning.

Fix conditions for specifying the organization_id variable
